name: C++ QTest CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use Windows/macOS if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.0'  # Adjust this to your Qt version

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y qtbase5-dev qt6-base-dev

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build/test --verbose

      - name: Run benchmarks
        run: |
          mkdir -p build/benchmarks
          cd build
          ./benchmark/mybenchmark -csv -o benchmarks/benchmark_results.csv

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: build/benchmarks/benchmark_results.csv